controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    antenna_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    r_arm_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    l_arm_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    forward_torque_controller:
      type: forward_command_controller/ForwardCommandController

    forward_fan_controller:
      type: forward_command_controller/ForwardCommandController

    pid_controller:
      type: pid_command_controller/PIDCommandController

    neck_forward_position_controller:
      type: forward_command_controller/ForwardCommandController


joint_state_broadcaster:
  ros__parameters:
    use_sim_time: false

neck_forward_position_controller:
  ros__parameters:
    joints:
      - neck_roll
      - neck_pitch
      - neck_yaw
    interface_name: position
    use_sim_time: false

r_arm_forward_position_controller:
  ros__parameters:
    joints:
      - r_shoulder_pitch
      - r_shoulder_roll
      - r_arm_yaw
      - r_elbow_pitch
      - r_forearm_yaw
      - r_wrist_pitch
      - r_wrist_roll
      - r_gripper
    interface_name: position
    use_sim_time: false

l_arm_forward_position_controller:
  ros__parameters:
    joints:
      - l_shoulder_pitch
      - l_shoulder_roll
      - l_arm_yaw
      - l_elbow_pitch
      - l_forearm_yaw
      - l_wrist_pitch
      - l_wrist_roll
      - l_gripper
    interface_name: position
    use_sim_time: false

antenna_forward_position_controller:
  ros__parameters:
    joints:
      - l_antenna
      - r_antenna
    interface_name: position
    use_sim_time: false

forward_torque_controller:
  ros__parameters:
    joints:
      - r_shoulder_pitch
      - r_shoulder_roll
      - r_arm_yaw
      - r_elbow_pitch
      - r_forearm_yaw
      - r_wrist_pitch
      - r_wrist_roll
      - r_gripper
      - l_shoulder_pitch
      - l_shoulder_roll
      - l_arm_yaw
      - l_elbow_pitch
      - l_forearm_yaw
      - l_wrist_pitch
      - l_wrist_roll
      - l_gripper
      - l_antenna
      - r_antenna
    interface_name: torque
    use_sim_time: false


pid_controller:
  ros__parameters:
    joints:
      - r_shoulder_pitch
      - r_shoulder_roll
      - r_arm_yaw
      - r_elbow_pitch
      - r_forearm_yaw
      - r_wrist_pitch
      - r_wrist_roll
      - r_gripper
      - l_shoulder_pitch
      - l_shoulder_roll
      - l_arm_yaw
      - l_elbow_pitch
      - l_forearm_yaw
      - l_wrist_pitch
      - l_wrist_roll
      - l_gripper
      - l_antenna
      - r_antenna
    use_sim_time: false


forward_fan_controller:
  ros__parameters:
    joints:
      - l_antenna_fan
      - r_antenna_fan
      - r_shoulder_fan
      - l_elbow_fan
      - r_wrist_fan
      - r_elbow_fan
      - l_wrist_fan
      - l_shoulder_fan
    interface_name: state
    use_sim_time: false