# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_controller
    - right_arm_controller
    - head_controller
    - left_gripper_controller
    - right_gripper_controller

  left_arm_controller:
    type: FollowJointTrajectory
    joints:
      - l_shoulder_pitch
      - l_shoulder_roll
      - l_arm_yaw
      - l_elbow_pitch
      - l_forearm_yaw
      - l_wrist_pitch
      - l_wrist_roll
    action_ns: follow_joint_trajectory
    default: true

  right_arm_controller:
    type: FollowJointTrajectory
    joints:
      - r_shoulder_pitch
      - r_shoulder_roll
      - r_arm_yaw
      - r_elbow_pitch
      - r_forearm_yaw
      - r_wrist_pitch
      - r_wrist_roll
    action_ns: follow_joint_trajectory
    default: true

  head_controller:
    type: FollowJointTrajectory
    joints:
      - neck_roll
      - neck_pitch
      - neck_yaw
    action_ns: follow_joint_trajectory
    default: true

  left_gripper_controller:
    type: FollowJointTrajectory
    joints:
      - l_gripper
    action_ns: follow_joint_trajectory
    default: true

  right_gripper_controller:
    type: FollowJointTrajectory
    joints:
      - r_gripper
    action_ns: follow_joint_trajectory
    default: true